"""Create the complete CAI PostgreSQL schema."""

from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE ia_classifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            conversation_id TEXT NOT NULL,
            message_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
            created_at TIMESTAMPTZ NOT NULL,
            full_context TEXT NOT NULL,
            message_count INTEGER NOT NULL,
            intent_type TEXT NOT NULL CHECK (intent_type IN (
                'question', 'problem', 'request', 'complaint', 'payment',
                'billing', 'financial', 'document', 'protocol', 'other'
            )),
            confidence DOUBLE PRECISION,
            title TEXT,
            protocol TEXT,
            description TEXT,
            department JSONB NOT NULL DEFAULT '[]'::jsonb,
            agent JSONB NOT NULL DEFAULT '[]'::jsonb,
            model TEXT NOT NULL,
            processing_time_ms INTEGER NOT NULL,
            prompt_version TEXT,
            reviewed_at TIMESTAMPTZ,
            reviewed_by TEXT,
            corrected_intent_type TEXT CHECK (
                corrected_intent_type IS NULL OR corrected_intent_type IN (
                    'question', 'problem', 'request', 'complaint', 'payment',
                    'billing', 'financial', 'document', 'protocol', 'other'
                )
            ),
            corrected_title TEXT,
            corrected_description TEXT,
            updated_at TIMESTAMPTZ
        );
        CREATE INDEX idx_ia_classifications_conversation_id
            ON ia_classifications(conversation_id);
        CREATE INDEX idx_ia_classifications_created_at
            ON ia_classifications(created_at);
        CREATE INDEX idx_ia_classifications_confidence
            ON ia_classifications(confidence);
        CREATE INDEX idx_ia_classifications_intent_type
            ON ia_classifications(intent_type);

        CREATE TABLE message_transcriptions (
            message_id TEXT PRIMARY KEY,
            conversation_id TEXT,
            text TEXT,
            model TEXT NOT NULL,
            status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
            attempt_count INTEGER NOT NULL DEFAULT 0,
            error_message TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            completed_at TIMESTAMPTZ
        );
        CREATE INDEX idx_message_transcriptions_conversation_id
            ON message_transcriptions(conversation_id);
        CREATE INDEX idx_message_transcriptions_status
            ON message_transcriptions(status);

        CREATE TABLE message_image_extractions (
            message_id TEXT PRIMARY KEY,
            conversation_id TEXT,
            text TEXT,
            model TEXT NOT NULL,
            status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
            attempt_count INTEGER NOT NULL DEFAULT 0,
            error_message TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            completed_at TIMESTAMPTZ
        );
        CREATE INDEX idx_message_image_extractions_conversation_id
            ON message_image_extractions(conversation_id);
        CREATE INDEX idx_message_image_extractions_status
            ON message_image_extractions(status);

        CREATE TABLE ticket_assignment_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            conversation_id TEXT NOT NULL,
            department_id TEXT,
            user_id TEXT,
            event_timestamp TIMESTAMPTZ NOT NULL,
            source_event_id TEXT,
            event_key TEXT NOT NULL UNIQUE,
            ticket_transfer_count INTEGER,
            created_at TIMESTAMPTZ NOT NULL
        );
        CREATE INDEX idx_ticket_assignment_history_conversation_time
            ON ticket_assignment_history(conversation_id, event_timestamp, id);

        CREATE TABLE ticket_assignment_event_keys (
            event_key TEXT PRIMARY KEY,
            conversation_id TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE digisac_departments (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            source_updated_at TIMESTAMPTZ,
            synced_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE digisac_users (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            source_updated_at TIMESTAMPTZ,
            synced_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE digisac_directory_sync_state (
            resource TEXT PRIMARY KEY,
            last_attempt_at TIMESTAMPTZ,
            last_success_at TIMESTAMPTZ
        );
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE digisac_directory_sync_state;
        DROP TABLE digisac_users;
        DROP TABLE digisac_departments;
        DROP TABLE ticket_assignment_event_keys;
        DROP TABLE ticket_assignment_history;
        DROP TABLE message_image_extractions;
        DROP TABLE message_transcriptions;
        DROP TABLE ia_classifications;
        """
    )
