"""Persist DigiSac conversation processing cycles and message membership."""

from alembic import op


revision = "0013_conversation_cycles"
down_revision = "0012_validate_event_fk"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE conversation_processing_cycles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id UUID NOT NULL,
            conversation_id TEXT NOT NULL,
            sequence_number INTEGER NOT NULL,
            protocol TEXT,
            cycle_started_at TIMESTAMPTZ,
            ticket_closed_at TIMESTAMPTZ,
            cycle_start_strategy TEXT NOT NULL,
            open_event_key TEXT,
            close_event_key TEXT,
            status TEXT NOT NULL,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            error_phase TEXT,
            error_message TEXT,
            warning_count INTEGER NOT NULL DEFAULT 0,
            snapshot_json JSONB,
            rendered_context TEXT,
            model_context TEXT,
            context_reduction_applied BOOLEAN NOT NULL DEFAULT FALSE,
            context_reduction_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            history_recovery_attempt INTEGER NOT NULL DEFAULT 0,
            history_page_count INTEGER NOT NULL DEFAULT 0,
            processing_time_ms INTEGER,
            classification_id BIGINT,
            next_attempt_at TIMESTAMPTZ,
            enqueued_at TIMESTAMPTZ,
            lease_owner TEXT,
            lease_expires_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            completed_at TIMESTAMPTZ,
            CONSTRAINT uq_conversation_cycles_public_id UNIQUE (public_id),
            CONSTRAINT uq_conversation_cycles_sequence
                UNIQUE (conversation_id, sequence_number),
            CONSTRAINT uq_conversation_cycles_open_event UNIQUE (open_event_key),
            CONSTRAINT uq_conversation_cycles_close_event UNIQUE (close_event_key),
            CONSTRAINT uq_conversation_cycles_classification UNIQUE (classification_id),
            CONSTRAINT fk_conversation_cycles_classification
                FOREIGN KEY (classification_id)
                REFERENCES ia_classifications(id) ON DELETE RESTRICT,
            CONSTRAINT ck_conversation_cycles_sequence_positive
                CHECK (sequence_number > 0),
            CONSTRAINT ck_conversation_cycles_attempt_nonnegative
                CHECK (attempt_count >= 0),
            CONSTRAINT ck_conversation_cycles_warning_nonnegative
                CHECK (warning_count >= 0),
            CONSTRAINT ck_conversation_cycles_status CHECK (status IN (
                'open', 'pending', 'recovering_messages', 'waiting_media',
                'building_context', 'summarizing', 'classifying',
                'completed', 'completed_with_warnings',
                'retryable_failure', 'failed'
            )),
            CONSTRAINT ck_conversation_cycles_public_id_nonzero
                CHECK (public_id <> '00000000-0000-0000-0000-000000000000'::uuid),
            CONSTRAINT ck_conversation_cycles_start_strategy_nonblank
                CHECK (btrim(cycle_start_strategy) <> ''),
            CONSTRAINT ck_conversation_cycles_open_key_nonblank
                CHECK (open_event_key IS NULL OR btrim(open_event_key) <> ''),
            CONSTRAINT ck_conversation_cycles_close_key_nonblank
                CHECK (close_event_key IS NULL OR btrim(close_event_key) <> '')
        );

        CREATE UNIQUE INDEX ux_conversation_cycles_one_open
            ON conversation_processing_cycles(conversation_id)
            WHERE ticket_closed_at IS NULL;
        CREATE INDEX idx_conversation_cycles_conversation_sequence
            ON conversation_processing_cycles(conversation_id, sequence_number DESC);
        CREATE INDEX idx_conversation_cycles_recovery
            ON conversation_processing_cycles(
                next_attempt_at, lease_expires_at, updated_at, id
            )
            WHERE status IN (
                'pending', 'recovering_messages', 'waiting_media',
                'building_context', 'summarizing', 'classifying',
                'retryable_failure'
            );

        CREATE TABLE conversation_cycle_messages (
            cycle_id BIGINT NOT NULL,
            message_id TEXT NOT NULL,
            position INTEGER NOT NULL,
            message_type TEXT NOT NULL,
            message_timestamp TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT pk_conversation_cycle_messages
                PRIMARY KEY (cycle_id, message_id),
            CONSTRAINT uq_conversation_cycle_messages_id UNIQUE (message_id),
            CONSTRAINT uq_conversation_cycle_messages_position
                UNIQUE (cycle_id, position),
            CONSTRAINT fk_conversation_cycle_messages_cycle
                FOREIGN KEY (cycle_id)
                REFERENCES conversation_processing_cycles(id) ON DELETE CASCADE,
            CONSTRAINT ck_conversation_cycle_messages_id_nonblank
                CHECK (btrim(message_id) <> ''),
            CONSTRAINT ck_conversation_cycle_messages_type_nonblank
                CHECK (btrim(message_type) <> ''),
            CONSTRAINT ck_conversation_cycle_messages_position_nonnegative
                CHECK (position >= 0)
        );
        CREATE INDEX idx_conversation_cycle_messages_message_cycle
            ON conversation_cycle_messages(message_id, cycle_id);
        """
    )


def downgrade() -> None:
    count = (
        op.get_bind()
        .exec_driver_sql("SELECT COUNT(*) FROM conversation_processing_cycles")
        .scalar_one()
    )
    if count:
        raise RuntimeError(
            "conversation processing cycles contain audit data; "
            "refusing a data-losing downgrade"
        )
    op.execute("DROP TABLE conversation_cycle_messages")
    op.execute("DROP TABLE conversation_processing_cycles")
