"""Add the durable Acessórias directory foundation."""

from alembic import op


revision = "0015_acessorias_directory"
down_revision = "0014_retry_scheduling"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE acessorias_companies (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            external_id TEXT NOT NULL,
            provider_id TEXT NOT NULL,
            legal_name TEXT NOT NULL DEFAULT '',
            trade_name TEXT NOT NULL DEFAULT '',
            provider_status TEXT,
            phone TEXT,
            uf TEXT,
            client_since TEXT,
            client_until TEXT,
            registered_at TEXT,
            source_updated_at TIMESTAMPTZ,
            is_present BOOLEAN NOT NULL DEFAULT TRUE,
            is_active BOOLEAN,
            synced_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_acessorias_companies_external_id UNIQUE (external_id),
            CONSTRAINT ck_acessorias_companies_external_id_nonblank
                CHECK (btrim(external_id) <> ''),
            CONSTRAINT ck_acessorias_companies_provider_id_nonblank
                CHECK (btrim(provider_id) <> '')
        );

        CREATE TABLE acessorias_departments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            external_id TEXT NOT NULL,
            name TEXT NOT NULL,
            responsible_name TEXT,
            responsible_email TEXT,
            provider_status TEXT,
            source_updated_at TIMESTAMPTZ,
            is_present BOOLEAN NOT NULL DEFAULT TRUE,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            synced_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_acessorias_departments_external_id UNIQUE (external_id),
            CONSTRAINT ck_acessorias_departments_external_id_nonblank
                CHECK (btrim(external_id) <> ''),
            CONSTRAINT ck_acessorias_departments_name_nonblank
                CHECK (btrim(name) <> '')
        );

        CREATE TABLE acessorias_company_contacts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id BIGINT NOT NULL REFERENCES acessorias_companies(id),
            external_key TEXT NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            raw_mobile TEXT,
            normalized_mobile TEXT,
            raw_email TEXT,
            normalized_email TEXT,
            is_present BOOLEAN NOT NULL DEFAULT TRUE,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            synced_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_acessorias_company_contacts_identity
                UNIQUE (company_id, external_key),
            CONSTRAINT ck_acessorias_company_contacts_external_key_nonblank
                CHECK (btrim(external_key) <> ''),
            CONSTRAINT ck_acessorias_company_contacts_mobile_digits
                CHECK (normalized_mobile IS NULL OR normalized_mobile ~ '^[0-9]+$')
        );

        CREATE TABLE acessorias_company_departments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id BIGINT NOT NULL REFERENCES acessorias_companies(id),
            department_id BIGINT NOT NULL REFERENCES acessorias_departments(id),
            is_present BOOLEAN NOT NULL DEFAULT TRUE,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            synced_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_acessorias_company_departments_pair
                UNIQUE (company_id, department_id)
        );

        CREATE TABLE acessorias_directory_sync_executions (
            execution_id UUID PRIMARY KEY,
            status TEXT NOT NULL,
            snapshot_hash TEXT,
            started_at TIMESTAMPTZ NOT NULL,
            completed_at TIMESTAMPTZ,
            page_count INTEGER NOT NULL DEFAULT 0,
            request_attempt_count INTEGER NOT NULL DEFAULT 0,
            company_count INTEGER NOT NULL DEFAULT 0,
            contact_count INTEGER NOT NULL DEFAULT 0,
            department_count INTEGER NOT NULL DEFAULT 0,
            relationship_count INTEGER NOT NULL DEFAULT 0,
            inactivated_count INTEGER NOT NULL DEFAULT 0,
            failure_category TEXT,
            failure_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_acessorias_sync_status CHECK (
                status IN ('started', 'succeeded', 'deduplicated', 'failed')
            ),
            CONSTRAINT ck_acessorias_sync_counts_nonnegative CHECK (
                page_count >= 0
                AND request_attempt_count >= 0
                AND company_count >= 0
                AND contact_count >= 0
                AND department_count >= 0
                AND relationship_count >= 0
                AND inactivated_count >= 0
            ),
            CONSTRAINT ck_acessorias_sync_snapshot_hash_nonblank CHECK (
                snapshot_hash IS NULL OR btrim(snapshot_hash) <> ''
            )
        );

        CREATE UNIQUE INDEX ux_acessorias_sync_success_snapshot
            ON acessorias_directory_sync_executions (snapshot_hash)
            WHERE status = 'succeeded';
        CREATE INDEX ix_acessorias_company_contacts_company
            ON acessorias_company_contacts (company_id);
        CREATE INDEX ix_acessorias_company_departments_department
            ON acessorias_company_departments (department_id);
        CREATE INDEX ix_acessorias_companies_presence
            ON acessorias_companies (is_present, is_active);
        CREATE INDEX ix_acessorias_departments_presence
            ON acessorias_departments (is_present, is_active);
        """
    )


def downgrade() -> None:
    connection = op.get_bind()
    populated = connection.exec_driver_sql(
        """
        SELECT EXISTS (SELECT 1 FROM acessorias_companies)
            OR EXISTS (SELECT 1 FROM acessorias_departments)
            OR EXISTS (SELECT 1 FROM acessorias_company_contacts)
            OR EXISTS (SELECT 1 FROM acessorias_company_departments)
            OR EXISTS (SELECT 1 FROM acessorias_directory_sync_executions)
        """
    ).scalar_one()
    if populated:
        raise RuntimeError(
            "Acessórias directory state exists; refusing a data-losing downgrade"
        )
    op.execute("DROP TABLE acessorias_company_departments")
    op.execute("DROP TABLE acessorias_company_contacts")
    op.execute("DROP TABLE acessorias_departments")
    op.execute("DROP TABLE acessorias_companies")
    op.execute("DROP TABLE acessorias_directory_sync_executions")
