"""Add durable DigiSac contact identity and hydration state."""

from alembic import op


revision = "0016_digisac_contact_identity"
down_revision = "0015_acessorias_directory"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE digisac_contacts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            external_id TEXT NOT NULL,
            name TEXT,
            alternative_name TEXT,
            internal_name TEXT,
            raw_number TEXT,
            normalized_number TEXT,
            is_group BOOLEAN,
            account_id TEXT,
            service_id TEXT,
            provider_created_at TIMESTAMPTZ,
            provider_updated_at TIMESTAMPTZ,
            provider_deleted_at TIMESTAMPTZ,
            last_seen_at TIMESTAMPTZ NOT NULL,
            last_source TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_digisac_contacts_external_id UNIQUE (external_id),
            CONSTRAINT ck_digisac_contacts_external_id_nonblank
                CHECK (btrim(external_id) <> ''),
            CONSTRAINT ck_digisac_contacts_normalized_number_digits
                CHECK (
                    normalized_number IS NULL
                    OR normalized_number ~ '^[0-9]+$'
                ),
            CONSTRAINT ck_digisac_contacts_source_nonblank
                CHECK (btrim(last_source) <> '')
        );

        CREATE TABLE digisac_contact_hydrations (
            contact_id BIGINT PRIMARY KEY REFERENCES digisac_contacts(id),
            status TEXT NOT NULL,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            requested_at TIMESTAMPTZ NOT NULL,
            last_attempt_at TIMESTAMPTZ,
            next_attempt_at TIMESTAMPTZ,
            lease_until TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            failure_category TEXT,
            failure_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_digisac_contact_hydrations_status CHECK (
                status IN ('pending', 'running', 'succeeded', 'failed')
            ),
            CONSTRAINT ck_digisac_contact_hydrations_attempts_nonnegative
                CHECK (attempt_count >= 0),
            CONSTRAINT ck_digisac_contact_hydrations_failure_category_safe
                CHECK (
                    failure_category IS NULL
                    OR failure_category ~ '^[a-z0-9_:-]+$'
                )
        );

        CREATE INDEX ix_digisac_contacts_provider_updated_at
            ON digisac_contacts (provider_updated_at);
        CREATE INDEX ix_digisac_contact_hydrations_due
            ON digisac_contact_hydrations (status, next_attempt_at, lease_until);
        """
    )


def downgrade() -> None:
    connection = op.get_bind()
    populated = connection.exec_driver_sql(
        """
        SELECT EXISTS (SELECT 1 FROM digisac_contact_hydrations)
            OR EXISTS (SELECT 1 FROM digisac_contacts)
        """
    ).scalar_one()
    if populated:
        raise RuntimeError(
            "DigiSac contact identity state exists; refusing a data-losing downgrade"
        )
    op.execute("DROP TABLE digisac_contact_hydrations")
    op.execute("DROP TABLE digisac_contacts")
