"""Add durable DigiSac-Acessorias identity evidence and resolution state."""

from alembic import op


revision = "0017_digisac_acessorias_identity"
down_revision = "0016_digisac_contact_identity"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE digisac_contacts
            ADD COLUMN raw_email TEXT,
            ADD COLUMN normalized_email TEXT;

        ALTER TABLE digisac_contacts
            ADD CONSTRAINT ck_digisac_contacts_normalized_email_nonblank
            CHECK (normalized_email IS NULL OR btrim(normalized_email) <> '');

        CREATE INDEX ix_digisac_contacts_normalized_email
            ON digisac_contacts (normalized_email);
        CREATE INDEX ix_digisac_contacts_normalized_number
            ON digisac_contacts (normalized_number);
        CREATE INDEX ix_acessorias_company_contacts_normalized_mobile
            ON acessorias_company_contacts (normalized_mobile)
            WHERE is_present IS TRUE AND is_active IS TRUE;
        CREATE INDEX ix_acessorias_company_contacts_normalized_email
            ON acessorias_company_contacts (normalized_email)
            WHERE is_present IS TRUE AND is_active IS TRUE;

        CREATE TABLE identity_match_evidence (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            digisac_contact_id BIGINT NOT NULL
                REFERENCES digisac_contacts(id) ON DELETE RESTRICT,
            acessorias_company_contact_id BIGINT NOT NULL
                REFERENCES acessorias_company_contacts(id) ON DELETE RESTRICT,
            acessorias_company_id BIGINT NOT NULL
                REFERENCES acessorias_companies(id) ON DELETE RESTRICT,
            evidence_type TEXT NOT NULL,
            value_fingerprint TEXT NOT NULL,
            source TEXT NOT NULL,
            rule_version TEXT NOT NULL,
            observed_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_identity_match_evidence_observation UNIQUE (
                digisac_contact_id,
                acessorias_company_contact_id,
                evidence_type,
                value_fingerprint,
                rule_version
            ),
            CONSTRAINT ck_identity_match_evidence_type CHECK (
                evidence_type IN (
                    'exact_phone', 'brazil_mobile_variant', 'exact_email'
                )
            ),
            CONSTRAINT ck_identity_match_evidence_fingerprint CHECK (
                value_fingerprint ~ '^[0-9a-f]{64}$'
            ),
            CONSTRAINT ck_identity_match_evidence_source_safe CHECK (
                source ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_identity_match_evidence_rule_safe CHECK (
                rule_version ~ '^[a-z0-9_.:-]+$'
            )
        );

        CREATE INDEX ix_identity_match_evidence_contact
            ON identity_match_evidence (digisac_contact_id);
        CREATE INDEX ix_identity_match_evidence_company
            ON identity_match_evidence (acessorias_company_id);
        CREATE INDEX ix_identity_match_evidence_contact_type
            ON identity_match_evidence (digisac_contact_id, evidence_type);

        CREATE TABLE identity_company_links (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            digisac_contact_id BIGINT NOT NULL
                REFERENCES digisac_contacts(id) ON DELETE RESTRICT,
            acessorias_company_id BIGINT NOT NULL
                REFERENCES acessorias_companies(id) ON DELETE RESTRICT,
            state TEXT NOT NULL,
            source TEXT NOT NULL,
            confirmation_source TEXT,
            confirmed_at TIMESTAMPTZ,
            confirmed_by TEXT,
            rejection_reason TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_identity_company_links_pair UNIQUE (
                digisac_contact_id, acessorias_company_id
            ),
            CONSTRAINT ck_identity_company_links_state CHECK (
                state IN ('candidate', 'confirmed', 'rejected')
            ),
            CONSTRAINT ck_identity_company_links_source_safe CHECK (
                source ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_identity_company_links_confirmation_safe CHECK (
                confirmation_source IS NULL
                OR confirmation_source ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_identity_company_links_rejection_safe CHECK (
                rejection_reason IS NULL
                OR rejection_reason ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_identity_company_links_rejection_state CHECK (
                (state = 'rejected'
                 AND rejection_reason IS NOT NULL
                 AND btrim(rejection_reason) <> '')
                OR (state <> 'rejected' AND rejection_reason IS NULL)
            ),
            CONSTRAINT ck_identity_company_links_confirmed_fields CHECK (
                (state = 'confirmed'
                 AND confirmation_source = 'manual_db'
                 AND confirmed_at IS NOT NULL)
                OR (state <> 'confirmed'
                    AND confirmed_at IS NULL
                    AND confirmation_source IS NULL)
            )
        );

        CREATE INDEX ix_identity_company_links_contact_state
            ON identity_company_links (digisac_contact_id, state);
        CREATE INDEX ix_identity_company_links_company
            ON identity_company_links (acessorias_company_id);

        CREATE TABLE identity_company_link_transitions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            link_id BIGINT NOT NULL
                REFERENCES identity_company_links(id) ON DELETE RESTRICT,
            from_state TEXT,
            to_state TEXT NOT NULL,
            source TEXT NOT NULL,
            reason TEXT NOT NULL,
            transition_key TEXT NOT NULL,
            confirmation_source TEXT,
            confirmed_at TIMESTAMPTZ,
            confirmed_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_identity_company_link_transition_key
                UNIQUE (transition_key),
            CONSTRAINT ck_identity_company_link_transition_from CHECK (
                from_state IS NULL
                OR from_state IN ('candidate', 'confirmed', 'rejected')
            ),
            CONSTRAINT ck_identity_company_link_transition_to CHECK (
                to_state IN ('candidate', 'confirmed', 'rejected')
            ),
            CONSTRAINT ck_identity_company_link_transition_source_safe CHECK (
                source ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_identity_company_link_transition_reason_safe CHECK (
                reason ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_identity_company_link_transition_confirmation_safe CHECK (
                confirmation_source IS NULL
                OR confirmation_source ~ '^[a-z0-9_:-]+$'
            )
        );

        CREATE INDEX ix_identity_company_link_transitions_link
            ON identity_company_link_transitions (link_id, created_at);

        CREATE TABLE conversation_cycle_identity_resolutions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cycle_id BIGINT NOT NULL
                REFERENCES conversation_processing_cycles(id) ON DELETE RESTRICT,
            digisac_contact_id BIGINT NOT NULL
                REFERENCES digisac_contacts(id) ON DELETE RESTRICT,
            state TEXT NOT NULL,
            origin TEXT NOT NULL,
            reason TEXT NOT NULL,
            link_id BIGINT
                REFERENCES identity_company_links(id) ON DELETE RESTRICT,
            resolved_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_conversation_cycle_identity_resolution_cycle
                UNIQUE (cycle_id),
            CONSTRAINT ck_conversation_cycle_identity_resolution_state CHECK (
                state IN ('confirmed', 'ambiguous', 'unresolved', 'conflict')
            ),
            CONSTRAINT ck_conversation_cycle_identity_resolution_origin_safe CHECK (
                origin ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_conversation_cycle_identity_resolution_reason_safe CHECK (
                reason ~ '^[a-z0-9_:-]+$'
            ),
            CONSTRAINT ck_conversation_cycle_identity_resolution_link CHECK (
                (state = 'confirmed' AND link_id IS NOT NULL)
                OR (state <> 'confirmed' AND link_id IS NULL)
            )
        );

        CREATE INDEX ix_conversation_cycle_identity_resolution_contact
            ON conversation_cycle_identity_resolutions (digisac_contact_id);
        CREATE INDEX ix_conversation_cycle_identity_resolution_state
            ON conversation_cycle_identity_resolutions (state);
        """
    )


def downgrade() -> None:
    connection = op.get_bind()
    populated = connection.exec_driver_sql(
        """
        SELECT EXISTS (SELECT 1 FROM conversation_cycle_identity_resolutions)
            OR EXISTS (SELECT 1 FROM identity_company_link_transitions)
            OR EXISTS (SELECT 1 FROM identity_company_links)
            OR EXISTS (SELECT 1 FROM identity_match_evidence)
            OR EXISTS (
                SELECT 1
                FROM digisac_contacts
                WHERE raw_email IS NOT NULL OR normalized_email IS NOT NULL
            )
        """
    ).scalar_one()
    if populated:
        raise RuntimeError(
            "DigiSac-Acessorias identity state exists; refusing a data-losing downgrade"
        )
    op.execute("DROP TABLE conversation_cycle_identity_resolutions")
    op.execute("DROP TABLE identity_company_link_transitions")
    op.execute("DROP TABLE identity_company_links")
    op.execute("DROP TABLE identity_match_evidence")
    op.execute("DROP INDEX ix_digisac_contacts_normalized_email")
    op.execute("DROP INDEX ix_digisac_contacts_normalized_number")
    op.execute(
        "DROP INDEX ix_acessorias_company_contacts_normalized_mobile"
    )
    op.execute(
        "DROP INDEX ix_acessorias_company_contacts_normalized_email"
    )
    op.execute(
        "ALTER TABLE digisac_contacts "
        "DROP CONSTRAINT ck_digisac_contacts_normalized_email_nonblank"
    )
    op.execute(
        "ALTER TABLE digisac_contacts DROP COLUMN raw_email, DROP COLUMN normalized_email"
    )
