"""Add durable DigiSac-to-Acessorias department mapping state."""

from alembic import op


revision = "0018_department_mapping"
down_revision = "0017_digisac_acessorias_identity"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE department_mapping_rules (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            digisac_department_external_id TEXT NOT NULL
                REFERENCES digisac_departments(id) ON DELETE RESTRICT,
            acessorias_department_external_id TEXT NOT NULL
                REFERENCES acessorias_departments(external_id) ON DELETE RESTRICT,
            version INTEGER NOT NULL,
            state TEXT NOT NULL,
            source TEXT NOT NULL,
            reason TEXT NOT NULL,
            actor TEXT,
            metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            effective_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_department_mapping_rule_version
                UNIQUE (digisac_department_external_id, version),
            CONSTRAINT ck_department_mapping_rule_source
                CHECK (source = 'manual_db'),
            CONSTRAINT ck_department_mapping_rule_ids_nonblank
                CHECK (
                    btrim(digisac_department_external_id) <> ''
                    AND btrim(acessorias_department_external_id) <> ''
                ),
            CONSTRAINT ck_department_mapping_rule_version_positive
                CHECK (version > 0),
            CONSTRAINT ck_department_mapping_rule_state
                CHECK (state IN ('active', 'inactive')),
            CONSTRAINT ck_department_mapping_rule_reason_safe
                CHECK (reason ~ '^[a-z0-9_:-]{1,120}$'),
            CONSTRAINT ck_department_mapping_rule_actor_safe
                CHECK (actor IS NULL OR actor ~ '^[a-z0-9_.:@-]{1,120}$'),
            CONSTRAINT ck_department_mapping_rule_metadata_object
                CHECK (jsonb_typeof(metadata_json) = 'object')
        );

        CREATE UNIQUE INDEX uq_department_mapping_rule_one_active
            ON department_mapping_rules (digisac_department_external_id)
            WHERE state = 'active';
        CREATE INDEX ix_department_mapping_rules_target
            ON department_mapping_rules (acessorias_department_external_id);
        CREATE INDEX ix_department_mapping_rules_state
            ON department_mapping_rules (state, digisac_department_external_id);

        CREATE TABLE department_mapping_transitions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            rule_id BIGINT NOT NULL
                REFERENCES department_mapping_rules(id) ON DELETE RESTRICT,
            from_state TEXT,
            to_state TEXT NOT NULL,
            source TEXT NOT NULL,
            reason TEXT NOT NULL,
            operation_key TEXT NOT NULL,
            actor TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_department_mapping_transition_operation
                UNIQUE (operation_key),
            CONSTRAINT ck_department_mapping_transition_from_state
                CHECK (from_state IS NULL OR from_state IN ('active', 'inactive')),
            CONSTRAINT ck_department_mapping_transition_to_state
                CHECK (to_state IN ('active', 'inactive')),
            CONSTRAINT ck_department_mapping_transition_source
                CHECK (source = 'manual_db'),
            CONSTRAINT ck_department_mapping_transition_reason_safe
                CHECK (reason ~ '^[a-z0-9_:-]{1,120}$'),
            CONSTRAINT ck_department_mapping_transition_operation_safe
                CHECK (operation_key ~ '^[a-z0-9_.:@-]{1,240}$'),
            CONSTRAINT ck_department_mapping_transition_actor_safe
                CHECK (actor IS NULL OR actor ~ '^[a-z0-9_.:@-]{1,120}$')
        );
        CREATE INDEX ix_department_mapping_transitions_rule
            ON department_mapping_transitions (rule_id, created_at, id);

        CREATE TABLE conversation_cycle_department_mappings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cycle_id BIGINT NOT NULL
                REFERENCES conversation_processing_cycles(id) ON DELETE RESTRICT,
            evaluation_key TEXT NOT NULL,
            rule_id BIGINT
                REFERENCES department_mapping_rules(id) ON DELETE RESTRICT,
            rule_version INTEGER,
            digisac_department_external_id TEXT,
            acessorias_department_external_id TEXT,
            company_id BIGINT
                REFERENCES acessorias_companies(id) ON DELETE RESTRICT,
            state TEXT NOT NULL,
            reason TEXT NOT NULL,
            validation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            evaluated_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_cycle_department_mapping_evaluation
                UNIQUE (cycle_id, evaluation_key),
            CONSTRAINT ck_cycle_department_mapping_evaluation_key
                CHECK (evaluation_key ~ '^[a-z0-9_.:@-]{1,240}$'),
            CONSTRAINT ck_cycle_department_mapping_state
                CHECK (state IN ('resolved', 'unresolved', 'invalid')),
            CONSTRAINT ck_cycle_department_mapping_reason_safe
                CHECK (reason ~ '^[a-z0-9_:-]{1,120}$'),
            CONSTRAINT ck_cycle_department_mapping_rule_version
                CHECK (rule_version IS NULL OR rule_version > 0),
            CONSTRAINT ck_cycle_department_mapping_ids_nonblank
                CHECK (
                    (digisac_department_external_id IS NULL
                     OR btrim(digisac_department_external_id) <> '')
                    AND (acessorias_department_external_id IS NULL
                     OR btrim(acessorias_department_external_id) <> '')
                ),
            CONSTRAINT ck_cycle_department_mapping_resolved_facts
                CHECK (
                    state <> 'resolved'
                    OR (
                        rule_id IS NOT NULL
                        AND rule_version IS NOT NULL
                        AND digisac_department_external_id IS NOT NULL
                        AND acessorias_department_external_id IS NOT NULL
                        AND company_id IS NOT NULL
                    )
                ),
            CONSTRAINT ck_cycle_department_mapping_validation_object
                CHECK (jsonb_typeof(validation_json) = 'object')
        );
        CREATE INDEX ix_cycle_department_mappings_cycle
            ON conversation_cycle_department_mappings (cycle_id, id);
        CREATE INDEX ix_cycle_department_mappings_state
            ON conversation_cycle_department_mappings (state, evaluated_at);
        """
    )


def downgrade() -> None:
    populated = op.get_bind().exec_driver_sql(
        """
        SELECT EXISTS (SELECT 1 FROM conversation_cycle_department_mappings)
            OR EXISTS (SELECT 1 FROM department_mapping_transitions)
            OR EXISTS (SELECT 1 FROM department_mapping_rules)
        """
    ).scalar_one()
    if populated:
        raise RuntimeError(
            "department mapping state exists; refusing a data-losing downgrade"
        )
    op.execute("DROP TABLE conversation_cycle_department_mappings")
    op.execute("DROP TABLE department_mapping_transitions")
    op.execute("DROP TABLE department_mapping_rules")
