"""Add durable Acessórias Request operations and manual reconciliation audit."""

from alembic import op


revision = "0019_acessorias_request_creation"
down_revision = "0018_department_mapping"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE acessorias_request_operations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_cycle_id BIGINT NOT NULL
                REFERENCES conversation_processing_cycles(id) ON DELETE RESTRICT,
            source_classification_id BIGINT
                REFERENCES ia_classifications(id) ON DELETE RESTRICT,
            conversation_id TEXT NOT NULL,
            company_id BIGINT
                REFERENCES acessorias_companies(id) ON DELETE RESTRICT,
            company_external_id TEXT,
            department_mapping_id BIGINT
                REFERENCES conversation_cycle_department_mappings(id)
                ON DELETE RESTRICT,
            department_external_id TEXT,
            payload_fingerprint TEXT,
            payload_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            state TEXT NOT NULL,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            claim_owner TEXT,
            claim_expires_at TIMESTAMPTZ,
            post_started_at TIMESTAMPTZ,
            first_attempt_at TIMESTAMPTZ,
            last_attempt_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            sol_id TEXT,
            last_provider_status INTEGER,
            failure_category TEXT,
            failure_message TEXT,
            reconciliation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_acessorias_request_operation_cycle
                UNIQUE (source_cycle_id),
            CONSTRAINT ck_acessorias_request_operation_conversation_nonblank
                CHECK (btrim(conversation_id) <> ''),
            CONSTRAINT ck_acessorias_request_operation_company_id_nonblank
                CHECK (
                    company_external_id IS NULL
                    OR btrim(company_external_id) <> ''
                ),
            CONSTRAINT ck_acessorias_request_operation_department_id_nonblank
                CHECK (
                    department_external_id IS NULL
                    OR btrim(department_external_id) <> ''
                ),
            CONSTRAINT ck_acessorias_request_operation_fingerprint
                CHECK (
                    payload_fingerprint IS NULL
                    OR payload_fingerprint ~ '^[0-9a-f]{64}$'
                ),
            CONSTRAINT ck_acessorias_request_operation_state
                CHECK (state IN (
                    'not_started', 'attempting', 'completed',
                    'definitive_failure', 'retryable_failure',
                    'reconciliation_required'
                )),
            CONSTRAINT ck_acessorias_request_operation_attempt_nonnegative
                CHECK (attempt_count >= 0),
            CONSTRAINT ck_acessorias_request_operation_claim_owner_safe
                CHECK (
                    claim_owner IS NULL
                    OR claim_owner ~ '^[a-zA-Z0-9_.:@-]{1,160}$'
                ),
            CONSTRAINT ck_acessorias_request_operation_sol_id_nonblank
                CHECK (sol_id IS NULL OR btrim(sol_id) <> ''),
            CONSTRAINT ck_acessorias_request_operation_failure_safe
                CHECK (
                    failure_category IS NULL
                    OR failure_category ~ '^[a-z0-9_:-]{1,120}$'
                ),
            CONSTRAINT ck_acessorias_request_operation_message_safe
                CHECK (
                    failure_message IS NULL
                    OR failure_message ~ '^[a-z0-9_:-]{1,240}$'
                ),
            CONSTRAINT ck_acessorias_request_operation_payload_object
                CHECK (jsonb_typeof(payload_metadata_json) = 'object'),
            CONSTRAINT ck_acessorias_request_operation_reconciliation_object
                CHECK (jsonb_typeof(reconciliation_json) = 'object'),
            CONSTRAINT ck_acessorias_request_operation_completed_identity
                CHECK (state <> 'completed' OR sol_id IS NOT NULL),
            CONSTRAINT ck_acessorias_request_operation_completed_timestamp
                CHECK (state <> 'completed' OR completed_at IS NOT NULL)
        );

        CREATE INDEX ix_acessorias_request_operations_state_recovery
            ON acessorias_request_operations (
                state, claim_expires_at, updated_at, id
            );
        CREATE INDEX ix_acessorias_request_operations_classification
            ON acessorias_request_operations (source_classification_id);
        CREATE INDEX ix_acessorias_request_operations_sol_id
            ON acessorias_request_operations (sol_id)
            WHERE sol_id IS NOT NULL;

        CREATE TABLE acessorias_request_reconciliations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            operation_id BIGINT NOT NULL
                REFERENCES acessorias_request_operations(id) ON DELETE RESTRICT,
            operation_key TEXT NOT NULL,
            action TEXT NOT NULL,
            source TEXT NOT NULL,
            sol_id TEXT,
            reason TEXT NOT NULL,
            actor TEXT,
            evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_acessorias_request_reconciliation_key
                UNIQUE (operation_key),
            CONSTRAINT ck_acessorias_request_reconciliation_key_safe
                CHECK (operation_key ~ '^[a-zA-Z0-9_.:@-]{1,240}$'),
            CONSTRAINT ck_acessorias_request_reconciliation_action
                CHECK (action IN ('record_solid', 'release_retry')),
            CONSTRAINT ck_acessorias_request_reconciliation_source
                CHECK (source = 'manual_db'),
            CONSTRAINT ck_acessorias_request_reconciliation_sol_id_nonblank
                CHECK (sol_id IS NULL OR btrim(sol_id) <> ''),
            CONSTRAINT ck_acessorias_request_reconciliation_reason_safe
                CHECK (reason ~ '^[a-z0-9_:-]{1,120}$'),
            CONSTRAINT ck_acessorias_request_reconciliation_actor_safe
                CHECK (
                    actor IS NULL
                    OR actor ~ '^[a-zA-Z0-9_.:@-]{1,160}$'
                ),
            CONSTRAINT ck_acessorias_request_reconciliation_evidence_object
                CHECK (jsonb_typeof(evidence_json) = 'object'),
            CONSTRAINT ck_acessorias_request_reconciliation_action_identity
                CHECK (
                    (action = 'record_solid' AND sol_id IS NOT NULL)
                    OR (action = 'release_retry' AND sol_id IS NULL)
                )
        );
        CREATE INDEX ix_acessorias_request_reconciliations_operation
            ON acessorias_request_reconciliations (operation_id, created_at, id);
        """
    )


def downgrade() -> None:
    connection = op.get_bind()
    populated = connection.exec_driver_sql(
        """
        SELECT EXISTS (SELECT 1 FROM acessorias_request_reconciliations)
            OR EXISTS (SELECT 1 FROM acessorias_request_operations)
        """
    ).scalar_one()
    if populated:
        raise RuntimeError(
            "Acessórias Request operations contain audit data; "
            "refusing a data-losing downgrade"
        )
    op.execute("DROP TABLE acessorias_request_reconciliations")
    op.execute("DROP TABLE acessorias_request_operations")
