"""Add durable idempotency for authenticated identity-link commands."""

from alembic import op


revision = "0021_identity_admin_commands"
down_revision = "0020_cycle_contact_provenance"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE identity_company_links
            DROP CONSTRAINT ck_identity_company_links_confirmed_fields;

        ALTER TABLE identity_company_links
            ADD CONSTRAINT ck_identity_company_links_confirmed_fields CHECK (
                (state = 'confirmed'
                 AND confirmation_source IN ('manual_db', 'admin_api')
                 AND confirmed_at IS NOT NULL)
                OR (state <> 'confirmed'
                    AND confirmed_at IS NULL
                    AND confirmation_source IS NULL)
            );

        CREATE TABLE identity_admin_commands (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            command_key_hash TEXT NOT NULL,
            operation TEXT NOT NULL,
            digisac_contact_id BIGINT NOT NULL
                REFERENCES digisac_contacts(id) ON DELETE RESTRICT,
            acessorias_company_id BIGINT NOT NULL
                REFERENCES acessorias_companies(id) ON DELETE RESTRICT,
            request_fingerprint TEXT NOT NULL,
            state TEXT NOT NULL DEFAULT 'processing',
            result_json JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            completed_at TIMESTAMPTZ,
            CONSTRAINT uq_identity_admin_commands_key_hash
                UNIQUE (command_key_hash),
            CONSTRAINT ck_identity_admin_commands_key_hash
                CHECK (command_key_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT ck_identity_admin_commands_operation
                CHECK (operation IN (
                    'identity_link_confirmation',
                    'identity_link_rejection'
                )),
            CONSTRAINT ck_identity_admin_commands_fingerprint
                CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
            CONSTRAINT ck_identity_admin_commands_state
                CHECK (state IN ('processing', 'completed')),
            CONSTRAINT ck_identity_admin_commands_result
                CHECK (
                    (state = 'processing'
                     AND result_json IS NULL
                     AND completed_at IS NULL)
                    OR (state = 'completed'
                        AND jsonb_typeof(result_json) = 'object'
                        AND completed_at IS NOT NULL)
                )
        );

        CREATE INDEX ix_identity_admin_commands_contact
            ON identity_admin_commands (digisac_contact_id, created_at);
        """
    )


def downgrade() -> None:
    populated = op.get_bind().exec_driver_sql(
        """
        SELECT EXISTS (SELECT 1 FROM identity_admin_commands)
            OR EXISTS (
                SELECT 1
                FROM identity_company_links
                WHERE state = 'confirmed' AND confirmation_source = 'admin_api'
            )
        """
    ).scalar_one()
    if populated:
        raise RuntimeError(
            "identity administrative command state exists; refusing a data-losing downgrade"
        )
    op.execute("DROP TABLE identity_admin_commands")
    op.execute(
        """
        ALTER TABLE identity_company_links
            DROP CONSTRAINT ck_identity_company_links_confirmed_fields;

        ALTER TABLE identity_company_links
            ADD CONSTRAINT ck_identity_company_links_confirmed_fields CHECK (
                (state = 'confirmed'
                 AND confirmation_source = 'manual_db'
                 AND confirmed_at IS NOT NULL)
                OR (state <> 'confirmed'
                    AND confirmed_at IS NULL
                    AND confirmation_source IS NULL)
            );
        """
    )
